# SPDX-FileCopyrightText: Public Domain
# SPDX-License-Identifier: CC0-1.0

name: Website

on:
  push:
    tags:
      - '**'

permissions:
  contents: read

jobs:
  publish:
    name: 'Build API documentation with PasDoc'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write            # to deploy to Pages
      id-token: write         # to verify the deployment originates from an appropriate source
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Setup PasDoc
        run: |
          irm -Uri https://github.com/pasdoc/pasdoc/releases/download/v1.0.4/pasdoc-1.0.4-win64.zip -OutFile pasdoc.zip
          7z x .\pasdoc.zip -o"$env:TEMP"

      - name: Build
        run: |
          $env:PATH += ";$env:TEMP\pasdoc\bin"
          cmd /c .\build_docs.cmd
          if (Test-Path -Path .\docs\cache) { rm -r -force .\docs\cache }

      - name: Setup GitHub Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload static assets
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './docs'
          retention-days: 30

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
